### ISSUE TITLE
Missing project license information

### ISSUE THREAD

**Issue by bryanlb** [WenweiGu/ISOLATE#1]
I ran across your paper via ACM, and was interested in exploring more with some of the strategies you suggested in ISOLATE. I noticed this repo was lacking license information however, and was wondering if that [could be added](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Comment by WenweiGu** [comment]
Hi, Bryan. Many thanks for your reminder. I have included the license now. You are welcome to contact me if you have further questions. 😊

**Comment by bryanlb** [comment]
Thanks for the quick update! I may reach out again in a few weeks once I've had the opportunity to benchmark this further with some of my datasets. 🙇
